### ISSUE TITLE
Crave for upstream credential settings.

### ISSUE THREAD

**Issue by zhongwm** [Centaur/repox#12]
upstream repository 配置需要能设置credentials，不然不能登录，不能下载依赖。

**Comment by Centaur** [comment]
Feature implemented in branch '#12', please checkout, test and report result.  Note, credentials should be set to `Connector` instead of `Upstream`

**Comment by zhongwm** [comment]
Good with Sonatype nexus repo

**Comment by zhongwm** [comment]
Error when build a sbt project proxied by repox @ branch #12
```
[error] impossible to get artifacts when data has not been loaded. IvyNode = org.springframework.security#spring-security-cas;3.1.2.RELEASE
java.lang.IllegalStateException: impossible to get artifacts when data has not been loaded. IvyNode = org.springframework.security#spring-security-cas;3.1.2.RELEASE
        at org.apache.ivy.core.resolve.IvyNode.getArtifacts(IvyNode.java:809)
        at org.apache.ivy.core.resolve.IvyNode.getSelectedArtifacts(IvyNode.java:786)
        at org.apache.ivy.core.report.ResolveReport.setDependencies(ResolveReport.java:235)
        at org.apache.ivy.core.resolve.ResolveEngine.resolve(ResolveEngine.java:235)
        at org.apache.ivy.Ivy.resolve(Ivy.java:517)
        at sbt.IvyActions$.sbt$IvyActions$$resolve(IvyActions.scala:266)
        at sbt.IvyActions$$anonfun$updateEither$1.apply(IvyActions.scala:175)
        at sbt.IvyActions$$anonfun$updateEither$1.apply(IvyActions.scala:157)
        at sbt.IvySbt$Module$$anonfun$withModule$1.apply(Ivy.scala:151)
        at sbt.IvySbt$Module$$anonfun$withModule$1.apply(Ivy.scala:151)
        at sbt.IvySbt$$anonfun$withIvy$1.apply(Ivy.scala:128)
        at sbt.IvySbt.sbt$IvySbt$$action$1(Ivy.scala:56)
        at sbt.IvySbt$$anon$4.call(Ivy.scala:64)
        at xsbt.boot.Locks$GlobalLock.withChannel$1(Locks.scala:93)
        at xsbt.boot.Locks$GlobalLock.xsbt$boot$Locks$GlobalLock$$withChannelRetries$1(Locks.scala:78)
        at xsbt.boot.Locks$GlobalLock$$anonfun$withFileLock$1.apply(Locks.scala:97)
        at xsbt.boot.Using$.withResource(Using.scala:10)
        at xsbt.boot.Using$.apply(Using.scala:9)
        at xsbt.boot.Locks$GlobalLock.ignoringDeadlockAvoided(Locks.scala:58)
        at xsbt.boot.Locks$GlobalLock.withLock(Locks.scala:48)
        at xsbt.boot.Locks$.apply0(Locks.scala:31)
        at xsbt.boot.Locks$.apply(Locks.scala:28)
        at sbt.IvySbt.withDefaultLogger(Ivy.scala:64)
        at sbt.IvySbt.withIvy(Ivy.scala:123)
        at sbt.IvySbt.withIvy(Ivy.scala:120)
        at sbt.IvySbt$Module.withModule(Ivy.scala:151)
        at sbt.IvyActions$.updateEither(IvyActions.scala:157)
        at sbt.Classpaths$$anonfun$sbt$Classpaths$$work$1$1.apply(Defaults.scala:1318)
        at sbt.Classpaths$$anonfun$sbt$Classpaths$$work$1$1.apply(Defaults.scala:1315)
        at sbt.Classpaths$$anonfun$doWork$1$1$$anonfun$85.apply(Defaults.scala:1345)
        at sbt.Classpaths$$anonfun$doWork$1$1$$anonfun$85.apply(Defaults.scala:1343)
        at sbt.Tracked$$anonfun$lastOutput$1.apply(Tracked.scala:35)
        at sbt.Classpaths$$anonfun$doWork$1$1.apply(Defaults.scala:1348)
        at sbt.Classpaths$$anonfun$doWork$1$1.apply(Defaults.scala:1342)
        at sbt.Tracked$$anonfun$inputChanged$1.apply(Tracked.scala:45)
        at sbt.Classpaths$.cachedUpdate(Defaults.scala:1360)
        at sbt.Classpaths$$anonfun$updateTask$1.apply(Defaults.scala:1300)
        at sbt.Classpaths$$anonfun$updateTask$1.apply(Defaults.scala:1275)
        at scala.Function1$$anonfun$compose$1.apply(Function1.scala:47)
        at sbt.$tilde$greater$$anonfun$$u2219$1.apply(TypeFunctions.scala:40)
        at sbt.std.Transform$$anon$4.work(System.scala:63)
        at sbt.Execute$$anonfun$submit$1$$anonfun$apply$1.apply(Execute.scala:226)
        at sbt.Execute$$anonfun$submit$1$$anonfun$apply$1.apply(Execute.scala:226)
        at sbt.ErrorHandling$.wideConvert(ErrorHandling.scala:17)
        at sbt.Execute.work(Execute.scala:235)
        at sbt.Execute$$anonfun$submit$1.apply(Execute.scala:226)
        at sbt.Execute$$anonfun$submit$1.apply(Execute.scala:226)
        at sbt.ConcurrentRestrictions$$anon$4$$anonfun$1.apply(ConcurrentRestrictions.scala:159)
        at sbt.CompletionService$$anon$2.call(CompletionService.scala:28)
        at java.util.concurrent.FutureTask.run(Unknown Source)
        at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
        at java.util.concurrent.FutureTask.run(Unknown Source)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
        at java.lang.Thread.run(Unknown Source)
[error] (*:update) java.lang.IllegalStateException: impossible to get artifacts when data has not been loaded. IvyNode = org.springframework.security#spring-security-cas;3.1.2.RELEASE
[error] Total time: 8 s, completed 2015-2-11 10:04:16
```
