### ISSUE TITLE
Error when  repository name contains illegal actor path name

### ISSUE THREAD

**Issue by Renkai** [Centaur/repox#28]
```
12-20 18:50:50.768 ERROR akka.actor.OneForOneStrategy akka://repox/user/RequestQueueMaster/HeadQueueWorker_1/HeadMaster_2
 Invalid actor path element [HeadWorker_patriknw at bintray_260118], illegal character [ ] at position: 19. Actor paths MUST: not start with `$`, include only ASCII letters and can only contain these special characters: -_.*$+:@&=,!~';.

akka.actor.InvalidActorNameException: Invalid actor path element [HeadWorker_patriknw at bintray_260118], illegal character [ ] at position: 19. Actor paths MUST: not start with `$`, include only ASCII letters and can only contain these special characters: -_.*$+:@&=,!~';.
        at akka.actor.ActorPath$.validatePathElement(ActorPath.scala:93) ~[repox-assembly-0.1-SNAPSHOT.jar:0.1-SNAPSHOT]
        at akka.actor.ActorPath$.validatePathElement(ActorPath.scala:75) ~[repox-assembly-0.1-SNAPSHOT.jar:0.1-SNAPSHOT]
        at akka.actor.dungeon.Children$class.checkName(Children.scala:182) ~[repox-assembly-0.1-SNAPSHOT.jar:0.1-SNAPSHOT]
        at akka.actor.dungeon.Children$class.actorOf(Children.scala:38) ~[repox-assembly-0.1-SNAPSHOT.jar:0.1-SNAPSHOT]
        at akka.actor.ActorCell.actorOf(ActorCell.scala:374) [repox-assembly-0.1-SNAPSHOT.jar:0.1-SNAPSHOT]
```

**Comment by Centaur** [comment]
Currently the actor names are generated using naive string concatenation. We need a specific naming rule.

**Comment by Centaur** [comment]
According to [this](https://github.com/akka/akka/blob/master/akka-actor/src/main/scala/akka/actor/ActorPath.scala#L48), just normalize this part of actor name with `URLEncoder.encode`.  Test code added.
