### ISSUE TITLE
添加代理时失败

### ISSUE THREAD

**Issue by loveyanbei** [Centaur/repox#38]
http 500.
发生在导入某个设置之后，应该是从公服的配置改的
java.lang.UnsupportedOperationException: empty.max
	at scala.collection.TraversableOnce$class.max(TraversableOnce.scala:229)
	at scala.collection.AbstractTraversable.max(Traversable.scala:104)
	at com.gtan.repox.data.ProxyServer$.nextId$lzycompute(ProxyServer.scala:19)
	at com.gtan.repox.data.ProxyServer$.nextId(ProxyServer.scala:19)
	at com.gtan.repox.config.ProxyPersister$NewOrUpdateProxy$$anonfun$2.apply(ProxyPersister.scala:13)
	at com.gtan.repox.config.ProxyPersister$NewOrUpdateProxy$$anonfun$2.apply(ProxyPersister.scala:13)
	at scala.Option.fold(Option.scala:158)
	at com.gtan.repox.config.ProxyPersister$NewOrUpdateProxy.transform(ProxyPersister.scala:13)
	at com.gtan.repox.config.ConfigPersister$$anonfun$2.applyOrElse(ConfigPersister.scala:128)
	at akka.actor.Actor$class.aroundReceive(Actor.scala:480)
	at com.gtan.repox.config.ConfigPersister.akka$persistence$Eventsourced$$super$aroundReceive(ConfigPersister.scala:57)
	at akka.persistence.Eventsourced$$anon$1.stateReceive(Eventsourced.scala:600)
	at akka.persistence.Eventsourced$class.aroundReceive(Eventsourced.scala:173)
	at com.gtan.repox.config.ConfigPersister.aroundReceive(ConfigPersister.scala:57)
	at akka.actor.ActorCell.receiveMessage(ActorCell.scala:526)
	at akka.actor.ActorCell.invoke(ActorCell.scala:495)
	at akka.dispatch.Mailbox.processMailbox(Mailbox.scala:257)
	at akka.dispatch.Mailbox.run(Mailbox.scala:224)
	at akka.dispatch.Mailbox.exec(Mailbox.scala:234)
	at scala.concurrent.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)
	at scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339)
	at scala.concurrent.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979)
	at scala.concurrent.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107)

**Comment by Centaur** [comment]
从异常判断是配置中的 `proxies` 被清空了，而自增 `id` 是从当前 `proxies` 配置中取 `id` 最大值然后 +1
Repox 的默认配置中包含有一项 proxyserver 设置作为模板，公服的配置中也有两个 proxyserver 配置项，在这个问题修复之前可以直接在这些配置项上修改，而不需要将其删除。
另外，“某个配置”，“应该是” 这样的语言没有信息量，下次可以发相应截图上来。Github 上传图片已经很方便了，拖进来就行。
