### ISSUE TITLE
按照指南无法在本地启动服务, log1-Slf4jLogger 没有响应, timeout

### ISSUE THREAD

**Issue by joshua-jin** [Centaur/repox#62]
按照指南编译并运行 repox 后，报错，具体信息如下:

`[WARN] [12/30/2016 14:08:53.394] [main] [EventStream(akka://repox)] Logger log1-Slf4jLogger did not respond within Timeout(5000 milliseconds) to InitializeLogger(bus)
error while starting up loggers
akka.ConfigurationException: Logger specified in config can't be loaded [akka.event.slf4j.Slf4jLogger] due to [akka.event.Logging$LoggerInitializationException: Logger log1-Slf4jLogger did not respond with LoggerInitialized, sent instead [TIMEOUT]]
	at akka.event.LoggingBus$$anonfun$4$$anonfun$apply$1.applyOrElse(Logging.scala:119)
	at akka.event.LoggingBus$$anonfun$4$$anonfun$apply$1.applyOrElse(Logging.scala:118)
	at scala.runtime.AbstractPartialFunction.apply(AbstractPartialFunction.scala:36)
	at scala.util.Failure$$anonfun$recover$1.apply(Try.scala:216)
	at scala.util.Try$.apply(Try.scala:192)
	at scala.util.Failure.recover(Try.scala:216)
	at akka.event.LoggingBus$$anonfun$4.apply(Logging.scala:118)
	at akka.event.LoggingBus$$anonfun$4.apply(Logging.scala:113)
	at scala.collection.TraversableLike$WithFilter$$anonfun$map$2.apply(TraversableLike.scala:683)
	at scala.collection.Iterator$class.foreach(Iterator.scala:893)
	at scala.collection.AbstractIterator.foreach(Iterator.scala:1336)
	at scala.collection.IterableLike$class.foreach(IterableLike.scala:72)
	at scala.collection.AbstractIterable.foreach(Iterable.scala:54)
	at scala.collection.TraversableLike$WithFilter.map(TraversableLike.scala:682)
	at akka.event.LoggingBus$class.startDefaultLoggers(Logging.scala:113)
	at akka.event.EventStream.startDefaultLoggers(EventStream.scala:28)
	at akka.actor.LocalActorRefProvider.init(ActorRefProvider.scala:667)
	at akka.actor.ActorSystemImpl.liftedTree2$1(ActorSystem.scala:657)
	at akka.actor.ActorSystemImpl._start$lzycompute(ActorSystem.scala:654)
	at akka.actor.ActorSystemImpl._start(ActorSystem.scala:654)
	at akka.actor.ActorSystemImpl.start(ActorSystem.scala:670)
	at akka.actor.ActorSystem$.apply(ActorSystem.scala:142)
	at akka.actor.ActorSystem$.apply(ActorSystem.scala:109)
	at com.gtan.repox.Repox$.<init>(Repox.scala:28)
	at com.gtan.repox.Repox$.<clinit>(Repox.scala:179)
	at com.gtan.repox.Main$.main(Main.scala:21)
	at com.gtan.repox.Main.main(Main.scala)
Caused by: akka.event.Logging$LoggerInitializationException: Logger log1-Slf4jLogger did not respond with LoggerInitialized, sent instead [TIMEOUT]
	at akka.event.LoggingBus$class.akka$event$LoggingBus$$addLogger(Logging.scala:188)
	at akka.event.LoggingBus$$anonfun$4$$anonfun$apply$4.apply(Logging.scala:117)
	at akka.event.LoggingBus$$anonfun$4$$anonfun$apply$4.apply(Logging.scala:116)
	at scala.util.Success$$anonfun$map$1.apply(Try.scala:237)
	at scala.util.Try$.apply(Try.scala:192)
	at scala.util.Success.map(Try.scala:237)
	at akka.event.LoggingBus$$anonfun$4.apply(Logging.scala:116)
	... 20 more
Exception in thread "main" java.lang.ExceptionInInitializerError
	at com.gtan.repox.Main$.main(Main.scala:21)
	at com.gtan.repox.Main.main(Main.scala)
Caused by: akka.ConfigurationException: Could not start logger due to [akka.ConfigurationException: Logger specified in config can't be loaded [akka.event.slf4j.Slf4jLogger] due to [akka.event.Logging$LoggerInitializationException: Logger log1-Slf4jLogger did not respond with LoggerInitialized, sent instead [TIMEOUT]]]
	at akka.event.LoggingBus$class.startDefaultLoggers(Logging.scala:147)
	at akka.event.EventStream.startDefaultLoggers(EventStream.scala:28)
	at akka.actor.LocalActorRefProvider.init(ActorRefProvider.scala:667)
	at akka.actor.ActorSystemImpl.liftedTree2$1(ActorSystem.scala:657)
	at akka.actor.ActorSystemImpl._start$lzycompute(ActorSystem.scala:654)
	at akka.actor.ActorSystemImpl._start(ActorSystem.scala:654)
	at akka.actor.ActorSystemImpl.start(ActorSystem.scala:670)
	at akka.actor.ActorSystem$.apply(ActorSystem.scala:142)
	at akka.actor.ActorSystem$.apply(ActorSystem.scala:109)
	at com.gtan.repox.Repox$.<init>(Repox.scala:28)
	at com.gtan.repox.Repox$.<clinit>(Repox.scala:179)
	... 2 more
12-30 14:08:53.491 INFO  akka.event.slf4j.Slf4jLogger
 Slf4jLogger started`

**Comment by Centaur** [comment]
http://stackoverflow.com/questions/29366986/akka-configuration-exception-logger-specified-cant-be-loaded 请自行在 application.conf 中修改相关设置。会不会机器太慢了 🤔

**Comment by joshua-jin** [comment]
应该不是机器的问题，是新款的 MBP，我修改参数再尝试一下。

**Comment by joshua-jin** [comment]
将 timeout 时间调整为 10s 后可以正常启动。
