### ISSUE TITLE
java.lang.IllegalArgumentException: requirement failed: package config

### ISSUE THREAD

**Issue by xb151652000** [Centaur/repox#63]
jdk 1.8  scala 2.12.1（单独解压的文件，配置的项目SDK）
系统Scala_path里面Scala 2.11.8

win7系统，idea 2016 和直接在文件操作也都试过，报错一样
对Scala项目不熟，新手，请见谅

java.lang.IllegalArgumentException: requirement failed: package config
        at scala.reflect.internal.Types$ModuleTypeRef.<init>(Types.scala:1879)
        at scala.reflect.internal.Types$PackageTypeRef.<init>(Types.scala:1897)
        at scala.reflect.internal.Types$TypeRef$.apply(Types.scala:2401)
        at scala.reflect.internal.Types.typeRef(Types.scala:3553)
        at scala.reflect.internal.Types.typeRef$(Types.scala:3536)
        at scala.reflect.internal.SymbolTable.typeRef(SymbolTable.scala:16)
        at scala.reflect.internal.Symbols$TypeSymbol.newTypeRef(Symbols.scala:3026)
        at scala.reflect.internal.Symbols$TypeSymbol.updateTypeCache(Symbols.scala:3079)
        at scala.reflect.internal.Symbols$TypeSymbol.maybeUpdateTypeCache(Symbols.scala:3065)
        at scala.reflect.internal.Symbols$TypeSymbol.tpe_$times(Symbols.scala:3043)
        at scala.reflect.internal.Symbols$Symbol.typeOfThis(Symbols.scala:2020)
        at scala.reflect.internal.Types$ThisType.underlying(Types.scala:1184)
        at scala.reflect.internal.Types$SimpleTypeProxy.boundSyms(Types.scala:150)
        at scala.reflect.internal.Types$SimpleTypeProxy.boundSyms$(Types.scala:150)
        at scala.reflect.internal.Types$SingletonType.boundSyms(Types.scala:1088)
        at scala.reflect.internal.tpe.TypeMaps$SubstMap.apply(TypeMaps.scala:734)
        at scala.reflect.internal.tpe.TypeMaps$SubstSymMap.apply(TypeMaps.scala:797)
        at scala.reflect.internal.tpe.TypeMaps$TypeMap.mapOver(TypeMaps.scala:110)
        at scala.reflect.internal.tpe.TypeMaps$SubstSymMap.apply(TypeMaps.scala:791)
        at scala.reflect.internal.Types$Type.substSym(Types.scala:727)
        at scala.reflect.internal.Symbols$Symbol.$anonfun$substInfo$1(Symbols.scala:1547)
        at scala.reflect.internal.Symbols$Symbol.modifyInfo(Symbols.scala:1540)
        at scala.reflect.internal.Symbols$Symbol.substInfo(Symbols.scala:1547)
        at scala.reflect.internal.Symbols.$anonfun$deriveSymbols$1(Symbols.scala:3532)
        at scala.reflect.internal.Symbols.deriveSymbols(Symbols.scala:3532)
        at scala.reflect.internal.Symbols.deriveSymbols$(Symbols.scala:3530)
        at scala.reflect.internal.SymbolTable.deriveSymbols(SymbolTable.scala:16)
        at scala.reflect.internal.Symbols.cloneSymbols(Symbols.scala:3592)
        at scala.reflect.internal.Symbols.cloneSymbols$(Symbols.scala:3591)
        at scala.reflect.internal.SymbolTable.cloneSymbols(SymbolTable.scala:16)
        at scala.reflect.internal.Symbols.cloneSymbolsAndModify(Symbols.scala:3603)
        at scala.reflect.internal.Symbols.cloneSymbolsAndModify$(Symbols.scala:3602)
        at scala.reflect.internal.SymbolTable.cloneSymbolsAndModify(SymbolTable.scala:16)
        at scala.reflect.internal.tpe.TypeMaps$TypeMap.mapOver(TypeMaps.scala:245)
        at scala.reflect.internal.tpe.TypeMaps$TypeMap.$anonfun$mapOver$1(TypeMaps.scala:128)
        at scala.reflect.internal.tpe.TypeMaps$TypeMap.mapOver(TypeMaps.scala:202)
        at scala.reflect.internal.transform.UnCurry$$anon$1.apply(UnCurry.scala:53)
        at scala.reflect.internal.transform.UnCurry.transformInfo(UnCurry.scala:154)
        at scala.reflect.internal.transform.UnCurry.transformInfo$(UnCurry.scala:148)
        at scala.tools.nsc.transform.UnCurry.transformInfo(UnCurry.scala:53)
        at scala.tools.nsc.transform.InfoTransform$Phase$$anon$1.transform(InfoTransform.scala:38)
        at scala.reflect.internal.Symbols$Symbol.rawInfo(Symbols.scala:1605)
        at scala.reflect.internal.Symbols$Symbol.info(Symbols.scala:1522)
        at scala.tools.nsc.transform.SpecializeTypes.$anonfun$specializeClass$31(SpecializeTypes.scala:808)
        at scala.tools.nsc.transform.SpecializeTypes.$anonfun$specializeClass$30(SpecializeTypes.scala:801)
        at scala.tools.nsc.transform.SpecializeTypes.specializeClass(SpecializeTypes.scala:799)
        at scala.tools.nsc.transform.SpecializeTypes.transformInfo(SpecializeTypes.scala:1215)
        at scala.tools.nsc.transform.InfoTransform$Phase$$anon$1.transform(InfoTransform.scala:38)
        at scala.reflect.internal.Symbols$Symbol.rawInfo(Symbols.scala:1605)
        at scala.reflect.internal.Symbols$Symbol.info(Symbols.scala:1522)
        at scala.reflect.internal.Symbols$Symbol.isDerivedValueClass(Symbols.scala:812)
        at scala.reflect.internal.Symbols$Symbol.isMethodWithExtension(Symbols.scala:815)
        at scala.tools.nsc.transform.ExplicitOuter$ExplicitOuterTransformer.transform(ExplicitOuter.scala:423)
        at scala.tools.nsc.transform.ExplicitOuter$ExplicitOuterTransformer.transform(ExplicitOuter.scala:323)
        at scala.reflect.internal.Trees.itransform(Trees.scala:1351)
        at scala.reflect.internal.Trees.itransform$(Trees.scala:1340)
        at scala.reflect.internal.SymbolTable.itransform(SymbolTable.scala:16)
        at scala.reflect.internal.SymbolTable.itransform(SymbolTable.scala:16)
        at scala.reflect.api.Trees$Transformer.transform(Trees.scala:2555)
        at scala.tools.nsc.transform.TypingTransformers$TypingTransformer.transform(TypingTransformers.scala:44)
        at scala.tools.nsc.transform.ExplicitOuter$OuterPathTransformer.scala$reflect$internal$Trees$UnderConstructionTransformer$$super$transform(ExplicitOuter.scala:205)
        at scala.reflect.internal.Trees$UnderConstructionTransformer.transform(Trees.scala:1699)
        at scala.reflect.internal.Trees$UnderConstructionTransformer.transform$(Trees.scala:1694)
        at scala.tools.nsc.transform.ExplicitOuter$OuterPathTransformer.transform(ExplicitOuter.scala:282)
        at scala.tools.nsc.transform.ExplicitOuter$ExplicitOuterTransformer.transform(ExplicitOuter.scala:470)
        at scala.tools.nsc.transform.ExplicitOuter$ExplicitOuterTransformer.transform(ExplicitOuter.scala:323)
        at scala.reflect.internal.Trees.$anonfun$itransform$1(Trees.scala:1361)
        at scala.tools.nsc.transform.TypingTransformers$TypingTransformer.atOwner(TypingTransformers.scala:30)
        at scala.tools.nsc.transform.TypingTransformers$TypingTransformer.atOwner(TypingTransformers.scala:25)
        at scala.reflect.internal.Trees.itransform(Trees.scala:1360)
        at scala.reflect.internal.Trees.itransform$(Trees.scala:1340)
        at scala.reflect.internal.SymbolTable.itransform(SymbolTable.scala:16)
        at scala.reflect.internal.SymbolTable.itransform(SymbolTable.scala:16)
        at scala.reflect.api.Trees$Transformer.transform(Trees.scala:2555)
        at scala.tools.nsc.transform.TypingTransformers$TypingTransformer.transform(TypingTransformers.scala:44)
        at scala.tools.nsc.transform.ExplicitOuter$OuterPathTransformer.scala$reflect$internal$Trees$UnderConstructionTransformer$$super$transform(ExplicitOuter.scala:205)
        at scala.reflect.internal.Trees$UnderConstructionTransformer.transform(Trees.scala:1699)
        at scala.reflect.internal.Trees$UnderConstructionTransformer.transform$(Trees.scala:1694)
        at scala.tools.nsc.transform.ExplicitOuter$OuterPathTransformer.transform(ExplicitOuter.scala:282)
        at scala.tools.nsc.transform.ExplicitOuter$ExplicitOuterTransformer.transform(ExplicitOuter.scala:470)
        at scala.tools.nsc.transform.ExplicitOuter$ExplicitOuterTransformer.transform(ExplicitOuter.scala:323)
        at scala.reflect.api.Trees$Transformer.$anonfun$transformStats$1(Trees.scala:2589)
        at scala.reflect.api.Trees$Transformer.transformStats(Trees.scala:2587)
        at scala.reflect.internal.Trees.itransform(Trees.scala:1370)
        at scala.reflect.internal.Trees.itransform$(Trees.scala:1340)
        at scala.reflect.internal.SymbolTable.itransform(SymbolTable.scala:16)
        at scala.reflect.internal.SymbolTable.itransform(SymbolTable.scala:16)
        at scala.reflect.api.Trees$Transformer.transform(Trees.scala:2555)
        at scala.tools.nsc.transform.TypingTransformers$TypingTransformer.transform(TypingTransformers.scala:44)
        at scala.tools.nsc.transform.ExplicitOuter$OuterPathTransformer.scala$reflect$internal$Trees$UnderConstructionTransformer$$super$transform(ExplicitOuter.scala:205)
        at scala.reflect.internal.Trees$UnderConstructionTransformer.transform(Trees.scala:1699)
        at scala.reflect.internal.Trees$UnderConstructionTransformer.transform$(Trees.scala:1694)
        at scala.tools.nsc.transform.ExplicitOuter$OuterPathTransformer.transform(ExplicitOuter.scala:282)
        at scala.tools.nsc.transform.ExplicitOuter$ExplicitOuterTransformer.transform(ExplicitOuter.scala:470)
        at scala.tools.nsc.transform.ExplicitOuter$ExplicitOuterTransformer.transform(ExplicitOuter.scala:323)
        at scala.reflect.internal.Trees.$anonfun$itransform$2(Trees.scala:1367)
        at scala.tools.nsc.transform.TypingTransformers$TypingTransformer.atOwner(TypingTransformers.scala:30)
        at scala.tools.nsc.transform.TypingTransformers$TypingTransformer.atOwner(TypingTransformers.scala:25)
        at scala.reflect.internal.Trees.itransform(Trees.scala:1365)
        at scala.reflect.internal.Trees.itransform$(Trees.scala:1340)
        at scala.reflect.internal.SymbolTable.itransform(SymbolTable.scala:16)
        at scala.reflect.internal.SymbolTable.itransform(SymbolTable.scala:16)
        at scala.reflect.api.Trees$Transformer.transform(Trees.scala:2555)
        at scala.tools.nsc.transform.TypingTransformers$TypingTransformer.transform(TypingTransformers.scala:44)
        at scala.tools.nsc.transform.ExplicitOuter$OuterPathTransformer.scala$reflect$internal$Trees$UnderConstructionTransformer$$super$transform(ExplicitOuter.scala:205)
        at scala.reflect.internal.Trees$UnderConstructionTransformer.transform(Trees.scala:1699)
        at scala.reflect.internal.Trees$UnderConstructionTransformer.transform$(Trees.scala:1694)
        at scala.tools.nsc.transform.ExplicitOuter$OuterPathTransformer.transform(ExplicitOuter.scala:282)
        at scala.tools.nsc.transform.ExplicitOuter$ExplicitOuterTransformer.transform(ExplicitOuter.scala:408)
        at scala.tools.nsc.transform.ExplicitOuter$ExplicitOuterTransformer.transform(ExplicitOuter.scala:323)
        at scala.reflect.api.Trees$Transformer.$anonfun$transformStats$1(Trees.scala:2589)
        at scala.reflect.api.Trees$Transformer.transformStats(Trees.scala:2587)
        at scala.reflect.internal.Trees.itransform(Trees.scala:1408)
        at scala.reflect.internal.Trees.itransform$(Trees.scala:1340)
        at scala.reflect.internal.SymbolTable.itransform(SymbolTable.scala:16)
        at scala.reflect.internal.SymbolTable.itransform(SymbolTable.scala:16)
        at scala.reflect.api.Trees$Transformer.transform(Trees.scala:2555)
        at scala.tools.nsc.transform.TypingTransformers$TypingTransformer.super$transform(TypingTransformers.scala:40)
        at scala.tools.nsc.transform.TypingTransformers$TypingTransformer.$anonfun$transform$1(TypingTransformers.scala:40)
        at scala.tools.nsc.transform.TypingTransformers$TypingTransformer.atOwner(TypingTransformers.scala:30)
        at scala.tools.nsc.transform.TypingTransformers$TypingTransformer.transform(TypingTransformers.scala:25)
        at scala.tools.nsc.transform.ExplicitOuter$OuterPathTransformer.scala$reflect$internal$Trees$UnderConstructionTransformer$$super$transform(ExplicitOuter.scala:205)
        at scala.reflect.internal.Trees$UnderConstructionTransformer.transform(Trees.scala:1699)
        at scala.reflect.internal.Trees$UnderConstructionTransformer.transform$(Trees.scala:1694)
        at scala.tools.nsc.transform.ExplicitOuter$OuterPathTransformer.transform(ExplicitOuter.scala:282)
        at scala.tools.nsc.transform.ExplicitOuter$ExplicitOuterTransformer.transform(ExplicitOuter.scala:384)
        at scala.tools.nsc.transform.ExplicitOuter$ExplicitOuterTransformer.transform(ExplicitOuter.scala:323)
        at scala.reflect.api.Trees$Transformer.transformTemplate(Trees.scala:2563)
        at scala.reflect.internal.Trees.$anonfun$itransform$4(Trees.scala:1412)
        at scala.tools.nsc.transform.TypingTransformers$TypingTransformer.atOwner(TypingTransformers.scala:30)
        at scala.tools.nsc.transform.TypingTransformers$TypingTransformer.atOwner(TypingTransformers.scala:25)
        at scala.reflect.internal.Trees.itransform(Trees.scala:1411)
        at scala.reflect.internal.Trees.itransform$(Trees.scala:1340)
        at scala.reflect.internal.SymbolTable.itransform(SymbolTable.scala:16)
        at scala.reflect.internal.SymbolTable.itransform(SymbolTable.scala:16)
        at scala.reflect.api.Trees$Transformer.transform(Trees.scala:2555)
        at scala.tools.nsc.transform.TypingTransformers$TypingTransformer.transform(TypingTransformers.scala:44)
        at scala.tools.nsc.transform.ExplicitOuter$OuterPathTransformer.scala$reflect$internal$Trees$UnderConstructionTransformer$$super$transform(ExplicitOuter.scala:205)
        at scala.reflect.internal.Trees$UnderConstructionTransformer.transform(Trees.scala:1699)
        at scala.reflect.internal.Trees$UnderConstructionTransformer.transform$(Trees.scala:1694)
        at scala.tools.nsc.transform.ExplicitOuter$OuterPathTransformer.transform(ExplicitOuter.scala:282)
        at scala.tools.nsc.transform.ExplicitOuter$ExplicitOuterTransformer.transform(ExplicitOuter.scala:470)
        at scala.tools.nsc.transform.ExplicitOuter$ExplicitOuterTransformer.transform(ExplicitOuter.scala:323)
        at scala.reflect.api.Trees$Transformer.$anonfun$transformStats$1(Trees.scala:2589)
        at scala.reflect.api.Trees$Transformer.transformStats(Trees.scala:2587)
        at scala.reflect.internal.Trees.$anonfun$itransform$7(Trees.scala:1430)
        at scala.tools.nsc.transform.TypingTransformers$TypingTransformer.atOwner(TypingTransformers.scala:30)
        at scala.tools.nsc.transform.TypingTransformers$TypingTransformer.atOwner(TypingTransformers.scala:25)
        at scala.reflect.internal.Trees.itransform(Trees.scala:1430)
        at scala.reflect.internal.Trees.itransform$(Trees.scala:1340)
        at scala.reflect.internal.SymbolTable.itransform(SymbolTable.scala:16)
        at scala.reflect.internal.SymbolTable.itransform(SymbolTable.scala:16)
        at scala.reflect.api.Trees$Transformer.transform(Trees.scala:2555)
        at scala.tools.nsc.transform.TypingTransformers$TypingTransformer.super$transform(TypingTransformers.scala:40)
        at scala.tools.nsc.transform.TypingTransformers$TypingTransformer.$anonfun$transform$2(TypingTransformers.scala:42)
        at scala.tools.nsc.transform.TypingTransformers$TypingTransformer.atOwner(TypingTransformers.scala:30)
        at scala.tools.nsc.transform.TypingTransformers$TypingTransformer.transform(TypingTransformers.scala:25)
        at scala.tools.nsc.transform.ExplicitOuter$OuterPathTransformer.scala$reflect$internal$Trees$UnderConstructionTransformer$$super$transform(ExplicitOuter.scala:205)
        at scala.reflect.internal.Trees$UnderConstructionTransformer.transform(Trees.scala:1699)
        at scala.reflect.internal.Trees$UnderConstructionTransformer.transform$(Trees.scala:1694)
        at scala.tools.nsc.transform.ExplicitOuter$OuterPathTransformer.transform(ExplicitOuter.scala:282)
        at scala.tools.nsc.transform.ExplicitOuter$ExplicitOuterTransformer.transform(ExplicitOuter.scala:470)
        at scala.tools.nsc.transform.ExplicitOuter$ExplicitOuterTransformer.transform(ExplicitOuter.scala:323)
        at scala.tools.nsc.ast.Trees$Transformer.transformUnit(Trees.scala:140)
        at scala.tools.nsc.transform.ExplicitOuter$ExplicitOuterTransformer.super$transformUnit(ExplicitOuter.scala:478)
        at scala.tools.nsc.transform.ExplicitOuter$ExplicitOuterTransformer.$anonfun$transformUnit$1(ExplicitOuter.scala:478)
        at scala.tools.nsc.transform.ExplicitOuter$ExplicitOuterTransformer.transformUnit(ExplicitOuter.scala:478)
        at scala.tools.nsc.transform.Transform$Phase.apply(Transform.scala:30)
        at scala.tools.nsc.Global$GlobalPhase.$anonfun$applyPhase$1(Global.scala:416)
        at scala.tools.nsc.Global$GlobalPhase.applyPhase(Global.scala:409)
        at scala.tools.nsc.Global$GlobalPhase.$anonfun$run$1(Global.scala:380)
        at scala.tools.nsc.Global$GlobalPhase.$anonfun$run$1$adapted(Global.scala:380)
        at scala.collection.Iterator.foreach(Iterator.scala:929)
        at scala.collection.Iterator.foreach$(Iterator.scala:929)
        at scala.collection.AbstractIterator.foreach(Iterator.scala:1406)
        at scala.tools.nsc.Global$GlobalPhase.run(Global.scala:380)
        at scala.tools.nsc.Global$Run.compileUnitsInternal(Global.scala:1418)
        at scala.tools.nsc.Global$Run.compileUnits(Global.scala:1403)
        at scala.tools.nsc.Global$Run.compileSources(Global.scala:1398)
        at scala.tools.nsc.Global$Run.compile(Global.scala:1492)
        at xsbt.CachedCompiler0.run(CompilerInterface.scala:116)
        at xsbt.CachedCompiler0.run(CompilerInterface.scala:95)
        at xsbt.CompilerInterface.run(CompilerInterface.scala:26)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at sbt.compiler.AnalyzingCompiler.call(AnalyzingCompiler.scala:107)
        at sbt.compiler.AnalyzingCompiler.compile(AnalyzingCompiler.scala:53)
        at sbt.compiler.AnalyzingCompiler.compile(AnalyzingCompiler.scala:47)
        at sbt.compiler.MixedAnalyzingCompiler$$anonfun$compileScala$1$1.apply$mcV$sp(MixedAnalyzingCompiler.scala:50)
        at sbt.compiler.MixedAnalyzingCompiler$$anonfun$compileScala$1$1.apply(MixedAnalyzingCompiler.scala:50)
        at sbt.compiler.MixedAnalyzingCompiler$$anonfun$compileScala$1$1.apply(MixedAnalyzingCompiler.scala:50)
        at sbt.compiler.MixedAnalyzingCompiler.timed(MixedAnalyzingCompiler.scala:74)
        at sbt.compiler.MixedAnalyzingCompiler.compileScala$1(MixedAnalyzingCompiler.scala:49)
        at sbt.compiler.MixedAnalyzingCompiler.compile(MixedAnalyzingCompiler.scala:64)
        at sbt.compiler.IC$$anonfun$compileInternal$1.apply(IncrementalCompiler.scala:160)
        at sbt.compiler.IC$$anonfun$compileInternal$1.apply(IncrementalCompiler.scala:160)
        at sbt.inc.IncrementalCompile$$anonfun$doCompile$1.apply(Compile.scala:66)
        at sbt.inc.IncrementalCompile$$anonfun$doCompile$1.apply(Compile.scala:64)
        at sbt.inc.IncrementalCommon.cycle(IncrementalCommon.scala:32)
        at sbt.inc.Incremental$$anonfun$1.apply(Incremental.scala:72)
        at sbt.inc.Incremental$$anonfun$1.apply(Incremental.scala:71)
        at sbt.inc.Incremental$.manageClassfiles(Incremental.scala:99)
        at sbt.inc.Incremental$.compile(Incremental.scala:71)
        at sbt.inc.IncrementalCompile$.apply(Compile.scala:54)
        at sbt.compiler.IC$.compileInternal(IncrementalCompiler.scala:160)
        at sbt.compiler.IC$.incrementalCompile(IncrementalCompiler.scala:138)
        at sbt.Compiler$.compile(Compiler.scala:155)
        at sbt.Compiler$.compile(Compiler.scala:141)
        at sbt.Defaults$.sbt$Defaults$$compileIncrementalTaskImpl(Defaults.scala:879)
        at sbt.Defaults$$anonfun$compileIncrementalTask$1.apply(Defaults.scala:870)
        at sbt.Defaults$$anonfun$compileIncrementalTask$1.apply(Defaults.scala:868)
        at scala.Function1$$anonfun$compose$1.apply(Function1.scala:47)
        at sbt.$tilde$greater$$anonfun$$u2219$1.apply(TypeFunctions.scala:40)
        at sbt.std.Transform$$anon$4.work(System.scala:63)
        at sbt.Execute$$anonfun$submit$1$$anonfun$apply$1.apply(Execute.scala:228)
        at sbt.Execute$$anonfun$submit$1$$anonfun$apply$1.apply(Execute.scala:228)
        at sbt.ErrorHandling$.wideConvert(ErrorHandling.scala:17)
        at sbt.Execute.work(Execute.scala:237)
        at sbt.Execute$$anonfun$submit$1.apply(Execute.scala:228)
        at sbt.Execute$$anonfun$submit$1.apply(Execute.scala:228)
        at sbt.ConcurrentRestrictions$$anon$4$$anonfun$1.apply(ConcurrentRestrictions.scala:159)
        at sbt.CompletionService$$anon$2.call(CompletionService.scala:28)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:745)
[error] (compile:compileIncremental) java.lang.IllegalArgumentException: requirement failed: package config
[error] Total time: 16 s, completed 2017-1-11 1:10:55

**Comment by Centaur** [comment]
类似的情况我在 Linux 上编译时也出现了。目前2.12版本只在 Mac 上编译成功，应该是 scala 2.12 的 bug

**Comment by Centaur** [comment]
根据此issue及 #64 反馈的情况和我自己的经历，发现此问题在所有平台上都能重现，而且**只要使用 [sbt-coursier 插件](https://github.com/alexarchambault/coursier) 就能规避此问题**，现在感觉更可能是 sbt 的 bug.

**Comment by xb151652000** [comment]
谢谢，成功解决。的确没想到是SBT的问题，感觉sbt_coursier就是并行下载的控件，所以没想往这边试。解决过程：
step1    找一个免费的VPN，下载基础包依赖包
step2    安装sbt_coursier控件
step3    参照quick start步骤重新执行一遍

**Comment by epiphyllum** [comment]
@xb151652000 

能把step1  step2  描述更加详细点么？   

我是mac上编译不了

**Comment by Centaur** [comment]
@epiphyllum [安装sbt-coursier插件](https://github.com/alexarchambault/coursier#sbt-plugin)后编译

**Comment by Centaur** [comment]
FYI, this issue is fixed after upgrade scala to 2.12.3, please checkout the latest code.
