### ISSUE TITLE
repox获取不到com.twitter.common#metrics;0.0.29，报not found，连的是公服

### ISSUE THREAD

**Issue by mingyu0519** [Centaur/repox#68]
日志
```
[info] Resolving com.twitter.common#metrics;0.0.29 ...
[error] Server access Error: Connection reset url=https://maven.twttr.com/com/twitter/common/metrics/0.0.29/metrics-0.0.29.pom
[warn] 	module not found: com.twitter.common#metrics;0.0.29
[warn] ==== local: tried
[warn]   /Users/user/.ivy2/local/com.twitter.common/metrics/0.0.29/ivys/ivy.xml
[warn] ==== repox-maven: tried
[warn]   http://repox.gtan.com:8078/com/twitter/common/metrics/0.0.29/metrics-0.0.29.pom
[warn] ==== repox-ivy: tried
[warn]   http://repox.gtan.com:8078/com.twitter.common/metrics/0.0.29/ivys/ivy.xml
[warn] ==== sonatype-releases: tried
[warn]   https://oss.sonatype.org/content/repositories/releases/com/twitter/common/metrics/0.0.29/metrics-0.0.29.pom
[warn] ==== public: tried
[warn]   https://repo1.maven.org/maven2/com/twitter/common/metrics/0.0.29/metrics-0.0.29.pom
[warn] ==== sonatype-snapshots: tried
[warn]   https://oss.sonatype.org/content/repositories/snapshots/com/twitter/common/metrics/0.0.29/metrics-0.0.29.pom
[warn] ==== Twitter's Repository: tried
[warn]   https://maven.twttr.com/com/twitter/common/metrics/0.0.29/metrics-0.0.29.pom
[info] Resolving com.fasterxml.jackson.module#jackson-module-scala_2.11;2.4.4 ..[info] Resolving jline#jline;2.12.1 ...
[warn] 	::::::::::::::::::::::::::::::::::::::::::::::
[warn] 	::          UNRESOLVED DEPENDENCIES         ::
[warn] 	::::::::::::::::::::::::::::::::::::::::::::::
[warn] 	:: com.twitter.common#metrics;0.0.29: not found
[warn] 	::::::::::::::::::::::::::::::::::::::::::::::
[warn]
[warn] 	Note: Unresolved dependencies path:
[warn] 		com.twitter.common:metrics:0.0.29
[warn] 		  +- com.twitter:finagle-stats_2.11:6.25.0
[warn] 		  +- com.twitter.inject:inject-server_2.11:2.0.0.M2 (/Users/user/tool/github/diffy/build.sbt#L52)
[warn] 		  +- com.twitter.finatra:finatra-utils_2.11:2.0.0.M2
[warn] 		  +- com.twitter.finatra:finatra-jackson_2.11:2.0.0.M2
[warn] 		  +- com.twitter.finatra:finatra-http_2.11:2.0.0.M2 (/Users/user/tool/github/diffy/build.sbt#L52)
[warn] 		  +- com.twitter:diffy_2.11:0.0.2-SNAPSHOT ()
sbt.ResolveException: unresolved dependency: com.twitter.common#metrics;0.0.29: not found
	at sbt.IvyActions$.sbt$IvyActions$$resolve(IvyActions.scala:294)
	at sbt.IvyActions$$anonfun$updateEither$1.apply(IvyActions.scala:191)
	at sbt.IvyActions$$anonfun$updateEither$1.apply(IvyActions.scala:168)
	at sbt.IvySbt$Module$$anonfun$withModule$1.apply(Ivy.scala:155)
	at sbt.IvySbt$Module$$anonfun$withModule$1.apply(Ivy.scala:155)
	at sbt.IvySbt$$anonfun$withIvy$1.apply(Ivy.scala:132)
	at sbt.IvySbt.sbt$IvySbt$$action$1(Ivy.scala:57)
	at sbt.IvySbt$$anon$4.call(Ivy.scala:65)
	at xsbt.boot.Locks$GlobalLock.withChannel$1(Locks.scala:93)
	at xsbt.boot.Locks$GlobalLock.xsbt$boot$Locks$GlobalLock$$withChannelRetries$1(Locks.scala:78)
	at xsbt.boot.Locks$GlobalLock$$anonfun$withFileLock$1.apply(Locks.scala:97)
	at xsbt.boot.Using$.withResource(Using.scala:10)
	at xsbt.boot.Using$.apply(Using.scala:9)
	at xsbt.boot.Locks$GlobalLock.ignoringDeadlockAvoided(Locks.scala:58)
	at xsbt.boot.Locks$GlobalLock.withLock(Locks.scala:48)
	at xsbt.boot.Locks$.apply0(Locks.scala:31)
	at xsbt.boot.Locks$.apply(Locks.scala:28)
	at sbt.IvySbt.withDefaultLogger(Ivy.scala:65)
	at sbt.IvySbt.withIvy(Ivy.scala:127)
	at sbt.IvySbt.withIvy(Ivy.scala:124)
	at sbt.IvySbt$Module.withModule(Ivy.scala:155)
	at sbt.IvyActions$.updateEither(IvyActions.scala:168)
	at sbt.Classpaths$$anonfun$sbt$Classpaths$$work$1$1.apply(Defaults.scala:1392)
	at sbt.Classpaths$$anonfun$sbt$Classpaths$$work$1$1.apply(Defaults.scala:1388)
	at sbt.Classpaths$$anonfun$doWork$1$1$$anonfun$90.apply(Defaults.scala:1422)
	at sbt.Classpaths$$anonfun$doWork$1$1$$anonfun$90.apply(Defaults.scala:1420)
	at sbt.Tracked$$anonfun$lastOutput$1.apply(Tracked.scala:37)
	at sbt.Classpaths$$anonfun$doWork$1$1.apply(Defaults.scala:1425)
	at sbt.Classpaths$$anonfun$doWork$1$1.apply(Defaults.scala:1419)
	at sbt.Tracked$$anonfun$inputChanged$1.apply(Tracked.scala:60)
	at sbt.Classpaths$.cachedUpdate(Defaults.scala:1442)
	at sbt.Classpaths$$anonfun$updateTask$1.apply(Defaults.scala:1371)
	at sbt.Classpaths$$anonfun$updateTask$1.apply(Defaults.scala:1325)
	at scala.Function1$$anonfun$compose$1.apply(Function1.scala:47)
	at sbt.$tilde$greater$$anonfun$$u2219$1.apply(TypeFunctions.scala:40)
	at sbt.std.Transform$$anon$4.work(System.scala:63)
	at sbt.Execute$$anonfun$submit$1$$anonfun$apply$1.apply(Execute.scala:226)
	at sbt.Execute$$anonfun$submit$1$$anonfun$apply$1.apply(Execute.scala:226)
	at sbt.ErrorHandling$.wideConvert(ErrorHandling.scala:17)
	at sbt.Execute.work(Execute.scala:235)
	at sbt.Execute$$anonfun$submit$1.apply(Execute.scala:226)
	at sbt.Execute$$anonfun$submit$1.apply(Execute.scala:226)
	at sbt.ConcurrentRestrictions$$anon$4$$anonfun$1.apply(ConcurrentRestrictions.scala:159)
	at sbt.CompletionService$$anon$2.call(CompletionService.scala:28)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
[error] (*:update) sbt.ResolveException: unresolved dependency: com.twitter.common#metrics;0.0.29: not found
[error] Total time: 25 s, completed 2017-2-13 18:32:15
```

**Comment by Centaur** [comment]
建议使用 0.0.38 版本。

**Comment by nannan1204** [comment]
Have you solve it? I had the same problem.
