### ISSUE TITLE
获取不到commons-io:commons-io:2.4

### ISSUE THREAD

**Issue by epiphyllum** [Centaur/repox#74]
```
[info] Resolving org.fusesource.jansi#jansi;1.4 ...
[warn] 	::::::::::::::::::::::::::::::::::::::::::::::
[warn] 	::          UNRESOLVED DEPENDENCIES         ::
[warn] 	::::::::::::::::::::::::::::::::::::::::::::::
[warn] 	:: commons-io#commons-io;2.4: configuration not found in commons-io#commons-io;2.4: 'master(compile)'. Missing configuration: 'compile'. It was required from org.vafer#jdeb;1.3 compile
[warn] 	::::::::::::::::::::::::::::::::::::::::::::::
[warn]
[warn] 	Note: Unresolved dependencies path:
[warn] 		commons-io:commons-io:2.4
[warn] 		  +- org.vafer:jdeb:1.3
[warn] 		  +- com.typesafe.sbt:sbt-native-packager:1.0.0 (scalaVersion=2.10, sbtVersion=0.13) (/Users/hary/workspace/scala/akka-in-action/chapter-conf-deploy/project/plugins.sbt#L1-2)
[warn] 		  +- default:chapter-conf-deploy-build:0.1-SNAPSHOT (scalaVersion=2.10, sbtVersion=0.13)
sbt.ResolveException: unresolved dependency: commons-io#commons-io;2.4: configuration not found in commons-io#commons-io;2.4: 'master(compile)'. Missing configuration: 'compile'. It was required from org.vafer#jdeb;1.3 compile
	at sbt.IvyActions$.sbt$IvyActions$$resolve(IvyActions.scala:313)
	at sbt.IvyActions$$anonfun$updateEither$1.apply(IvyActions.scala:191)
	at sbt.IvyActions$$anonfun$updateEither$1.apply(IvyActions.scala:168)
	at sbt.IvySbt$Module$$anonfun$withModule$1.apply(Ivy.scala:156)
	at sbt.IvySbt$Module$$anonfun$withModule$1.apply(Ivy.scala:156)
	at sbt.IvySbt$$anonfun$withIvy$1.apply(Ivy.scala:133)
	at sbt.IvySbt.sbt$IvySbt$$action$1(Ivy.scala:57)
	at sbt.IvySbt$$anon$4.call(Ivy.scala:65)
```

**Comment by Centaur** [comment]
尝试了一下，依赖 `"commons-io" % "commons-io" % "2.4"` 可以正常 resolve，请检查你的sbt配置。如果自己无法发现问题，请把 sbt 文件贴上来我帮你检查。
